### ISSUE TITLE
Cursor is always hidden

### ISSUE THREAD

**Issue by p00f** [karb94/neoscroll.nvim#1]
Cursor is hidden even when not scrolling and with `neoscroll_hide_cursor_line = 0`
I even tried defining `neoscroll_hide_cursor_line` before loading plugins:
`init.lua` - 
```lua
local api = vim.api

api.nvim_command("packadd packer.nvim")
vim.o.termguicolors = true
vim.g["conjure#mapping#doc_word"] = "K"
vim.g.neoscroll_hide_cursor_line = 0
local packer = require("packer")
local packages = require("packages")

packer.startup(function()
    for _, value in pairs(packages) do
        packer.use(value)
    end
end)
```

**Comment by karb94** [comment]
Could you pull the latest changes and try again? I might have fixed the issue.

**Comment by p00f** [comment]
It's always visible now :)

**Comment by karb94** [comment]
Just for future reference, I changed `g:neoscroll_hide_cursor_line` to `g:neoscroll_hide_cursor` to make its purpose clearer

**Comment by p00f** [comment]
I mean, I can't hide it using `neoscroll_hide_cursor` now

**Comment by karb94** [comment]
Oops, sorry for the missunderstanding. As explained in the docs, hiding the cursor only works if you have `'termguicolors'` set (which it is not set by default). Try:
```
set termguicolors
```
It can be hard to see if your cursor is actually hiding with low time steps. Try increasing them to make sure it is not hiding while scrolling.

If this doesn't work post the result of `set guicursor`.

**Comment by p00f** [comment]
I have termguicolors set, the steps are default, my screen refresh rate is 60 Hz, guicursor is `guicursor=n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20,a:blinkon700`

**Comment by karb94** [comment]
Can't seem to reproduce the issue... If you run `set guicursor+=a:NeoscrollHiddenCursor` does your cursor hide? If it does hide, can you provide a minimal config that reproduces the issue?

**Comment by p00f** [comment]
It does hide yeah. I'll try it on a minimal config soon

**Comment by p00f** [comment]
My bad, it is clearly hidden when I use C-f/b.
