### ISSUE TITLE
Pre-scrolling and post-scrolling hooks

### ISSUE THREAD

**Issue by karb94** [karb94/neoscroll.nvim#10]
Trigger a custom User autocommands before and after scrolling. Maybe separate events depending on the type of scroll or alternatively (and probably better) exposing different variables from the plugin that users can use to trigger actions depending on the scrolling state.

Please comment if you are interested in seeing this implemented an how you would use it so that I have a clearer idea of what needs to be done.

**Comment by chriskisskiss** [comment]
when doing half page/page scrolls it would be great to see my target line in the process of scrolling. I tried it with
`
  let line = line('.') + &scroll
  let id = matchadd('Search', '\%'.line.'l')
  lua require('neoscroll').scroll(vim.wo.scroll, true, 250)
  call matchdelete(id) ← for this a post scroll hook would be great
`

**Comment by karb94** [comment]
@chriskisskiss  I just added pre-scrolling and post-scrolling hooks. Read the docs  and let me know if anything is not clear or doesn't work as expected. You can find a quick example in the [README](https://github.com/karb94/neoscroll.nvim#pre_hook-and-post_hook-functions).
