### ISSUE TITLE
zt and zb broke with scroll refactor

### ISSUE THREAD

**Issue by DavidRambo** [karb94/neoscroll.nvim#101]
Hello,
Trying to use zt or zb results in the following error:
```
E5108: Error executing lua ...al/share/nvim/lazy/neoscroll.nvim/lua/neoscroll/init.lua:174: attempt
to call field 'get_scrolloff' (a nil value)
stack traceback:
        ...al/share/nvim/lazy/neoscroll.nvim/lua/neoscroll/init.lua:174: in function 'zt'
        [string ":lua"]:1: in main chunk
```

I believe I have resolved it: both functions in init.lua call `window.get_scrolloff`, which mirrors the previous `utils.get_scrolloff`. Changing it to `window.scrolloff` seems to fix it.

I'll submit a PR in a moment. Though of course no need to merge it if you'd rather fix it yourself : )

**Comment by karb94** [comment]
Thanks, PR accepted!
