### ISSUE TITLE
Latest commit (88e63a8) issues

### ISSUE THREAD

**Issue by cdmill** [karb94/neoscroll.nvim#103]
After updating to the latest commit I'm running into a few issues.

My previous config (below) now has errors because line 17 in `neoscroll/config.lua` is expecting a table but is getting `nil`. The docs still use `require("neoscroll").setup()` in the quickstart section, so I don't think this is intended. This error will obviously go away if passing an empty table or any custom opts.

```lua
  {
    "karb94/neoscroll.nvim",
    event = { "BufReadPost", "BufNewFile" },
    config = function()
      require("neoscroll").setup()
    end,
  },
```

If the error is ignored then no scrolling animations happen. If i pass a table (empty or with custom opts) and then for example use `zb`  I get the following error happening in `neoscroll/init.lua` line 298 "attempting to perform arithmetic on local 'half_win_duration' ( a table value)".

**Comment by srirambtechit** [comment]
I'm getting the very same error after update.

```
Failed to run `config` for neoscroll.nvim

.../share/nvim/lazy/neoscroll.nvim/lua/neoscroll/config.lua:17: bad argument #1 to 'pairs' (table expected, got nil)
```

Any fix is much appreciated.

**Comment by agusdmb** [comment]
same here

**Comment by b0ae989c** [comment]
Some new interfaces have bugs in `duration` calculation. For example: https://github.com/karb94/neoscroll.nvim/blob/88e63a89fee0f6112f0477a5709a460c45e5dee9/lua/neoscroll/init.lua#L242C31-L242C48

**Comment by b0ae989c** [comment]
Update: these bugs don't affect many users because they remove all default mappings, and set up mappings with `require('neoscroll.config').set_mappings`, which calls the bug-free `<cmd>` interfaces.

**Comment by karb94** [comment]
Sorry about this. I'll fix it in a few hours.

**Comment by karb94** [comment]
Let me know if the last commit didn't fix all of your issues.

**Comment by joelpeapen** [comment]
i have this config:
```lua
local scroll = require("neoscroll")
scroll.setup({
    mappings = { "zt", "zz", "zb" }
})
local mappings = {
    ["<m-j>"] = function() scroll.ctrl_d({ time = 100 }) end,
    ["<m-k>"] = function() scroll.ctrl_u({ time = 100 }) end,
    ["<m-h>"] = function() scroll.scroll(0.1, { move_cursor=false; time = 100 }) end,
    ["<m-;>"] = function() scroll.scroll(-0.1, { move_cursor=false; time = 100 }) end,
}
for key, func in pairs(mappings) do
  MAP({'n', 'v', 'x'}, key, func)
end
```

and this error
> E5108: Error executing lua: .../share/nvim/lazy/neoscroll.nvim/lua/neoscroll/scroll.lua:127: attempt to perform arithmetic on field 'duration' (a nil value)   
> stack traceback:                                                                                                                                               
>         .../share/nvim/lazy/neoscroll.nvim/lua/neoscroll/scroll.lua:127: in function 'compute_time_step'                                                       
>         ...al/share/nvim/lazy/neoscroll.nvim/lua/neoscroll/init.lua:179: in function 'new_scroll'                                                              
>         ...al/share/nvim/lazy/neoscroll.nvim/lua/neoscroll/init.lua:102: in function 'scroll'                                                                  
>         ...al/share/nvim/lazy/neoscroll.nvim/lua/neoscroll/init.lua:201: in function 'ctrl_d'
