### ISSUE TITLE
Feature request: add toggle command

### ISSUE THREAD

**Issue by redxtech** [karb94/neoscroll.nvim#109]
Would it be possible to add a command to toggle smooth scrolling?

Something like `:NeoScroll <toggle|enable|disable>`, so you could choose whether its enabled at any point, without having to go to your config, change it, and then restart vim.

**Comment by karb94** [comment]
I think this is out of scope for this plugin. Imagine that someone for some reason had some mappings already defined before enabling Neoscroll. That would mean that Neoscroll would have to store those mappings to be able to restore them later on if this toggle were to exist. I know this sounds like a very niche edge case but I'm sure someone will come asking for it at some point.

It's not difficult to create your own toggle. Feel free to ask for help if you can't figure it out.
