### ISSUE TITLE
Move cursor with page when scrolling

### ISSUE THREAD

**Issue by bfulop** [karb94/neoscroll.nvim#12]
Hello,

Thanks for this great plugin, it's working pretty great even on my 4K monitor (with Kitty)!

I have a question about the configuration. Currently I have this setup in my `init.lua` based on the latest commits:

```lua
neoscroll.setup({
  mappings = {'<C-u>', '<C-d>', '<C-b>',
    '<C-f>', '<C-y>', '<C-e>', 'zz'},
  hide_cursor = true,          
  stop_eof = false,             
  respect_scrolloff = true,   
  cursor_scrolls_alone = false,  
})
```

and remapped some keys like this:

```lua
utils.nnoremap('<C-y>', ":lua require('neoscroll').scroll(-3, true, 12)<cr>")
utils.nnoremap('<C-e>', ":lua require('neoscroll').scroll(3, true, 12)<cr>")
```

I really liked before that with vim, when you scroll one line up, the cursor stayed on the same _line number_.
If it was on line `42` and you scroll up 3 lines it will still be on line `42`. (or was it because of _vim-smoothie_ ? 🤔)

Do you think it's possible to get the same behaviour with neoscroll ? I tried `cursor_scrolls_alone` with `true|false` but didn't see a difference.

**Comment by bfulop** [comment]
Ah sorry for the false alert,  I've found the tweak ! 

Needed to set the second argument to `false` 👍 

```lua
utils.nnoremap('<C-y>', ":lua require('neoscroll').scroll(-3, false, 12)<cr>")
utils.nnoremap('<C-e>', ":lua require('neoscroll').scroll(3, false, 12)<cr>")
```

**Comment by karb94** [comment]
I love it when issues get resolved before I look at them :smile:.

Just as a tip, you might prefer to give a fraction as the first argument instead of a number. For instance, if you pass `0.05` instead of `3` it will move 5% of the window's height. This way if you split the window or your window size gets reduced for whatever reason you will still scroll the same percentage of the screen instead of a fixed number of lines.

**Comment by bfulop** [comment]
😅 

Yes actually this was intentional. I prefer to just scroll a few lines on `<c-y>` and on a big screen it was moving too much. Maybe I'll experiment with smaller fractions, than the default ones.
