### ISSUE TITLE
C-b and C-f not working

### ISSUE THREAD

**Issue by AckslD** [karb94/neoscroll.nvim#18]
Just installed neoscroll with default settings. `<C-d>` and `<C-u>` work really nice but `<C-b>` and `<C-f>` doesn't, any idea why that could be? By not working I mean that they do what they are supposed to do but without smooth scrolling.

Looking at `:map` I see for example:
```
x  <C-B>       * <Cmd>lua require('neoscroll').scroll(-vim.api.nvim_win_get_height(0), true, 7)<CR>                                                                           
n  <C-B>       * <Cmd>lua require('neoscroll').scroll(-vim.api.nvim_win_get_height(0), true, 7)<CR>                                                                           
...                                                                                                                                      
x  <C-D>       * <Cmd>lua require('neoscroll').scroll(vim.wo.scroll, true, 8)<CR>                                                                                             
n  <C-D>       * <Cmd>lua require('neoscroll').scroll(vim.wo.scroll, true, 8)<CR>                                                                                             
x  <C-E>       * <Cmd>lua require('neoscroll').scroll(0.10, false, 20)<CR>                                                                                                    
n  <C-E>       * <Cmd>lua require('neoscroll').scroll(0.10, false, 20)<CR>                                                                                                    
x  <C-F>       * <Cmd>lua require('neoscroll').scroll(vim.api.nvim_win_get_height(0), true, 7)<CR>                                                                            
n  <C-F>       * <Cmd>lua require('neoscroll').scroll(vim.api.nvim_win_get_height(0), true, 7)<CR>  
```

**Comment by karb94** [comment]
Strange... If you run `:lua require('neoscroll').scroll(vim.api.nvim_win_get_height(0), true, 7)` I assume it does scroll the screen right? There isn't any big differences between `<C-d>`/`<C-u>` and `<C-f>`/`<C-b>` mappings. It's the same function with different arguments. Your best bet is to start with a clean init file and keep adding parts of your config until you find the problem. If it still doesn't work with a minimal init file then post it here and I'll take a look. For now I cannot reproduce the problem.

**Comment by AckslD** [comment]
Thanks for your reply @karb94!

Seems the issue was with these two lines:
```
    -- scroll down hover doc or scroll in definition preview
    buf_set_keymap('n', '<C-f>', "<Cmd>lua require('lspsaga.action').smart_scroll_with_saga(1)<CR>", opts)
    -- scroll up hover doc
    buf_set_keymap('n', '<C-b>', "<Cmd>lua require('lspsaga.action').smart_scroll_with_saga(-1)<CR>", opts)
```
from [lspsaga](https://github.com/glepnir/lspsaga.nvim#hover-doc). Any thoughts on how one could make that compatible :) Not really an issue with neoscroll but just wondering if you know a solution to also use the smart scroll of saga in preview windows.
