### ISSUE TITLE
Move cursor instantly for <C-u> and similar

### ISSUE THREAD

**Issue by Shatur95** [karb94/neoscroll.nvim#20]
At the moment, the cursor animates with screen movement and mess up macroses. I also personally find this behavior less comfortable.
It would be better if the cursor moves instantly and the screen moves smoothly. There is awesome [scroll.vim](https://github.com/mg979/scroll.vim) in Vimscript that do the same thing.
It would be awesome to have an option for this or even make this as a default behavior.

**Comment by karb94** [comment]
Can you give some more details about how this would work? Are you suggesting to move the cursor instantaneously before or after smoothly scrolling the screen? I assume you are saying to move the cursor first. I've never seen this behaviour in the previous scrolling plugins I tried and to be honest it sounds a bit weird to me.

I think you could obtain a similar behaviour by just adding a movement command (like `20j`) before the scrolling function and then just set the `move_cursor` argument to `false`. Give some more details about the behaviour you want and I can be more specific.

**Comment by Shatur95** [comment]
> Can you give some more details about how this would work? Are you suggesting to move the cursor instantaneously before or after smoothly scrolling the screen? I assume you are saying to move the cursor first.

Yes. At least I thought so. I took a closer look and scroll.vim just has more scrolling speed. Sorry for bothering :)

**Comment by karb94** [comment]
You can also change the scrolling speed in this plugin by changing the `time_step` argument of the `scroll()` function. If you need any guidance let me know
