### ISSUE TITLE
Error on neovim startup

### ISSUE THREAD

**Issue by ddiegosr** [karb94/neoscroll.nvim#25]
I getting an error on neovim startup after install the plugin.

- Neovim version: NVIM v0.4.4
- Package manager: vim-plug
- Startup: init.vim

## Here's the error
```
Error detected while processing  ~/.config/nvim/init.vim:
line    5:
E5105: Error while calling lua chunk: ...onfig/nvim/plugged/neoscroll.nvim/lua/neoscroll/init.lua:8: attempt to call field 'nvim_exec' (a nil value)
Press ENTER or type command to continue
```

## Content in `init.vim`
```
call plug#begin()
  Plug 'karb94/neoscroll.nvim'
call plug#end()

lua require('neoscroll').setup()
```

**Comment by karb94** [comment]
As the [README.md](https://github.com/karb94/neoscroll.nvim#installation) states, this plugin only works for version 0.5.
