### ISSUE TITLE
Video in README.md seems to be corrupt.

### ISSUE THREAD

**Issue by Xithrius** [karb94/neoscroll.nvim#26]
Mozilla Firefox 89.0, Linux 5.12.8-1-MANJARO

![image](https://user-images.githubusercontent.com/15021300/121086300-d73cb080-c797-11eb-94c0-d03936302f65.png)

**Comment by karb94** [comment]
mmm works fine on chromium so it's probably a Github bug. Not sure how I can fix this on my end. I want to keep the repo as light as possible so including the video file as part of the repo is not an option.

**Comment by Xithrius** [comment]
Thank you for the reply, and keeping this repo very light.

Maybe a gif could be embedded instead from giphy or imgur in the markdown file? Although I can see how relying on an outside source for a video to work wouldn't be the best.

Have a good one!

**Comment by kosayoda** [comment]
Tracked down the issue. The video uploaded uses YUV444 chroma subsampling, which is not supported in Firefox.

```
$ ffprobe flawed.mp4
ffprobe version n4.4 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10.2.0 (GCC)

<-- snip -->

  Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 1266x1424, 3182 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
```

Instead, for web compatibility YUV420 should be used for h264 encoded files.
```
$ ffmpeg -i flawed.mp4 -pix_fmt yuv420p fixed.mp4
```

https://user-images.githubusercontent.com/41782385/121794472-fd040280-cc3a-11eb-9e76-43f7986567b8.mp4

Further reading: https://bugzilla.mozilla.org/show_bug.cgi?id=1368063

**Comment by karb94** [comment]
@kosayoda thank you for tracking down the issue and fixing the video for me. I updated the README.
