### ISSUE TITLE
Error ... attempt to index a nil value

### ISSUE THREAD

**Issue by daiyanze** [karb94/neoscroll.nvim#31]
### Detail
Recently I've encountered an unexpected error when I press down CTRL+D to scroll down. Same error happened to <CTRL>+U.
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/14920529/122907746-6a780780-d38e-11eb-928e-5f4dcae29ba1.png">

Thought this commit caused issue.
1de7d035c6bbcf367d96954a02b248b4fedc5978

I also tried with some former commits, they are all good to me.

### How to reproduce
Open any file and press down CTRL+D. The page doesn't scroll down at all.

**Comment by karb94** [comment]
Can you pull the latest commit? There's a high chance that was causing the issue. Let me know how it goes.

**Comment by daiyanze** [comment]
@karb94 The latest commit is working. There's no error anymore. Thank you!

**Comment by bitterjug** [comment]
I just got the same error. I installed with 

```vim
  Plug 'karb94/neoscroll.nvim'
```
And ran `
```vim
:lua require('neoscroll').setup()`
```
from the command line. 

Now <c-u>, <c-d>, <c-f>, <c-b>give
```
E5108: Error executing lua ...onfig/nvim/plugged/neoscroll.nvim/lua/neoscroll/init.lua:306: attempt to index a nil value
```

I'm guessing I have the latest commit from master if I just installed. 
What might be going wrong?

**Comment by karb94** [comment]
@bitterjug can you open a new issue? I don't think it's related to this one. Some initial questions:

- Does this issue happen with a minimal config as well?
- Could you make sure you are up to date? I don't see how line 306 would give any trouble.
- Does this happen every time you trigger a scroll or only some times?
