### ISSUE TITLE
Normal command argument error following scrolloff changes

### ISSUE THREAD

**Issue by akinsho** [karb94/neoscroll.nvim#32]
Hi 👋🏾 ,

Thanks for your work on this plugin I've been using if for a while now and it's been really smooth sailing. Recently some changes relating to `scrolloff` have been added which seem to have triggered a new error in my setup which then causes the cursor to remain hidden.
When I scroll using `<c-d>` , `<c-u>` I see
```
E5108: Error executing lua .../pack/packer/start/neoscroll.nvim/lua/neoscroll/init.lua:198: Vim(normal):E471: Argument required: normal!
```
I have some scrolloff options in my init.lua specifically
```lua
vim.opt.scrolloff = 9
vim.opt.sidescrolloff = 10
vim.opt.sidescroll = 1
```
Removing these doesn't seem to help though and the error occurs anyway.
I have this plugin configured using
```lua
        require("neoscroll").setup {
          mappings = { "<C-u>", "<C-d>", "<C-b>", "<C-f>", "<C-y>", "zt", "zz", "zb" },
          stop_eof = false,
        }
```

I noticed this after the most recent change in master so rolled back to the last working commit which was the one before the `scrolloff` change. I also briefly noticed this a few days ago when I think a similar change was introduced then reverted.

Let me know if I can provide any more information.

**Comment by babygau** [comment]
I understand this is relate to #11 and #28 but `vim.wo.scrolloff=0` doesn't fix this issue

**Comment by karb94** [comment]
@akinsho did you pull the latest commit (4cb8fe7)? I think with your config should work out of the box. Otherwise try [this](https://github.com/karb94/neoscroll.nvim/issues/33#issuecomment-866727385) proposed solution by @babygau.

PS: @babygau thank you for helping me with the issues.

**Comment by akinsho** [comment]
@karb94 just to clarify, it was 4cb8fe7 that created the problem for me. I just tried out the workaround in the linked issue, and it doesn't work on my end, unfortunately. I still get this error. Should I be setting the `opt_local` in each ft or? I've just added it to my init.lua settings. Also, should it be required since I though `vim.opt` set local and global both as required?

**Comment by babygau** [comment]
@akinsho, this should work unless you restore `nvim` from a session (this happened to me too). Another workaround is to use `autocmd`, eg: `vim.cmd[[autocmd BufEnter * setlocal so=0]]`

PS: @karb94 it's my pleasure

**Comment by akinsho** [comment]
@babygau yeah that's probably the issue i.e. sessions, I use them extensively. Guessing I need to delete all of them 😓 . Maybe the workaround wouldn't be needed if I cleared my session. Will give it a try and feedback

**Comment by akinsho** [comment]
Just tried clearing my sessions and can confirm it works out of the box without the workaround 👍🏾 thanks both for your help. Maybe something for the README but also maybe not if it's a one off fluke

**Comment by folke** [comment]
@karb94 after restoring sessions, the global scrolloff is still wrong.

You can use `vim.go.scrolloff` to get the correct value instead of the `o` scope.

**Comment by akinsho** [comment]
FWIW I spoke too soon, the moment I opened a new window without the workaround the bug cropped up.

**Comment by folke** [comment]
@akinsho added a PR for the one letter change 😂

**Comment by akinsho** [comment]
Thanks @folke 🥇

**Comment by karb94** [comment]
I actually had `go` at the begining and I changed it to `o` cause I thought it was wrong. These option scopes and scrolloff issues can be quite confusing specially with the recent changes. I won't be able to test anything for a few days so thank you for the PR.

**Comment by akinsho** [comment]
Seems to have resolved things on my end 👍🏾

**Comment by folke** [comment]
@karb94 yeah, it's definitely a bit confusing right now. Also with `vim.opt` and the api functions to set options.
