### ISSUE TITLE
Expose API

### ISSUE THREAD

**Issue by RaafatTurki** [karb94/neoscroll.nvim#34]
expose the lua functions as an api so one can trigger a scroll however they desire

**Comment by karb94** [comment]
Can you expand on this? The `scroll()` function is already exposed and ready to use. What use case do you have in mind?

**Comment by RaafatTurki** [comment]
Actually now that I've took a 2nd look at the README I see that you've edited the (custom mappings)[https://github.com/karb94/neoscroll.nvim#custom-mappings] section which explains the `scroll()` function way more clearly, excuse my outdated knowledge, an old time user here.

**Comment by karb94** [comment]
No worries. Remember to read the docs too. They have more precise information aboit how the functions work.
