### ISSUE TITLE
Uncancellable scroll if pressed for a while

### ISSUE THREAD

**Issue by oblitum** [karb94/neoscroll.nvim#38]
Scroll animation gets stuck/uncancellable if scroll mapping is kept pressed for a while for continuous scroll. It should be able to cancel when user types another key or there's another event.

**Comment by karb94** [comment]
You can cancel the scroll by scrolling once in the opposite direction. This will stop the scrolling smoothly.

**Comment by oblitum** [comment]
uh, okay, that works, though... it would be more natural if it could be cancelled by additional means, like cursor movement maybe?

**Comment by oblitum** [comment]
Also, actually, I believe current implementation is not correct in the sense that, it should not accumulate scrolling like it's doing now, it should start stop scrolling smoothly right on release of scrolling keys.

**Comment by oblitum** [comment]
I'm reopening due to considering that an implementation issue. Feel free to close if you think I'm wrong at that.

**Comment by karb94** [comment]
> it should not accumulate scrolling like it's doing now, it should start stop scrolling smoothly right on release of scrolling keys

To my knowledge, (neo)vim doesn't handle key release events so what you are describing is not possible. Therefore you need a more explicit mechanism to tell neovim to stop scrolling like the current implementation. It's not perfect but it's the best I could come up with and I'm very much opened to hear other approaches.

>or right after last triggering

How can I know when is your last trigger? 

>it should not accumulate scrolling like it's doing now

Accumulating the scrolling lines allows you to press `c-f` twice to scroll two screens, etc. It also allows you to quickly rectify a misstyped scroll, e.g. if you press `c-d` and you want to cancel it you can press `c-u` again to go back to the original position. If you don't accumulate the scrolling lines you wouldn't have these nice behaviours.

>it would be more natural if it could be cancelled by additional means, like cursor movement maybe?

This is a good suggestion but I don't know if it's possible. I will do some research.

Also if you have tried other scrolling plugins that handle this better let me know how they approach this and I'll consider their approach.

**Comment by oblitum** [comment]
I've tried vim-smoothie before, but it had different issues, it changed original easing function and became lame due to becoming very slow to stop scrolling. Yours is on point on that aspect, unless when key is kept pressed. You should agree with me, it doesn't make much sense that due to holding keys, which will generate a lot of key repeats, each of those key repeats should be stored to trigger a smooth scroll event. The first action at that seems to impose some limit on how long the easing function should keep running on its own when the use stopped interacting, currently I stop interacting and can keep running for very long time.

**Comment by karb94** [comment]
>The first action at that seems to impose some limit on how long the easing function should keep running on its own when the user stops interacting, currently I stop interacting and it can keep running on its own for very long time.

Fair, what do you suggest? Maybe stop accumulating after 3x scrolls? I don't think I would go lower than that (i.e. 2x)

**Comment by oblitum** [comment]
@karb94 you can pick a default, but what about making it an option, maybe called `inertia`?

**Comment by karb94** [comment]
checkout 2b0d9b2 and see if it suits your needs.

**Comment by oblitum** [comment]
It's much better now, thx.

**Comment by oblitum** [comment]
fwiw, when I suggested the `inertia` option, I was thinking of "a given amount to accumulate scrolling" instead of a Boolean option.

**Comment by karb94** [comment]
I think this is the kind of thing that if done right it should please everyone and an option is not necessary. 

The way it works now is that whenever the scrolling accumulates more than 5 times it will change it to 2 times and cap it so that whenever you stop repeating the scrolling input it will take less than two scrolls to finish the animation. It can be a bit inconsistent on how much time the scrolling animation takes to stop but that's the nature of only capturing key presses and not key releases.
