### ISSUE TITLE
Missing cursor after scroll

### ISSUE THREAD

**Issue by JoseConseco** [karb94/neoscroll.nvim#42]
The problem I have is - after using 'ctrl+d' or 'ctrl+u' the cursor sometimes disappears. 
I'm not 100% if that is caused by neoscroll but  disabling neoscroll - fixes the issue:

https://user-images.githubusercontent.com/13521338/126875834-f0c16d00-d5f7-4585-8fd8-ea0e35a3896f.mp4
Ignore the view port glitches caused by poor recording software. 
Looks like scrolling worked ok 2 days ago, but I do not see any commits that could cause the issue.  Maybe somebody can reproduce the issue?  I think it is neoscroll that makes the cursor transparent during scroll right?

**Comment by JoseConseco** [comment]
it seems using :   'hide_cursor = true ' in  plugins setup()  its good workaround for now.

**Comment by karb94** [comment]
Could you post the output of `:set guicursor` in the following situations:
- Before scrolling
- After scrolling when your cursor reappears as usual.
- After scrolling when your cursor doesn't reappear

Also share the config you had when that happened please.

I did change the structure of the code a few days ago so I might have inadvertedly created a new bug but I haven't experienced your issue so far.

The `hide_cursor` option is true by default so I don't see how that is going to help you.

**Comment by JoseConseco** [comment]
Before scroll:
![image](https://user-images.githubusercontent.com/13521338/126879677-49399cdc-abad-42ee-9df0-80660ab16220.png)
After scroll but cursor visible:
![image](https://user-images.githubusercontent.com/13521338/126879685-d5e9977d-1eff-427f-8eca-5b09c769e30e.png)
After scroll and cursor missing:
![image](https://user-images.githubusercontent.com/13521338/126879778-ed65ee59-c4da-46d2-970e-d6f9c1786d0c.png)

Any my bad - I meant    'hide_cursor' = false - fixes the issue.  My default config is empty:
-  require('neoscroll').setup({})

**Comment by JoseConseco** [comment]
Ok I think I found why this happens - when I have folds enabled - then cursor randomly disappears, but If I enable all folds then cursor works okl.
'zi'  -  hotkey to toggle code folding.
'zc' - folds code

**Comment by karb94** [comment]
I still cannot reproduce it. Going over folds is nothing special for Neoscroll so I don't see how that would affect it. Have you tried this with a minimal config? Maybe some other plugin/config is interfering.

**Comment by MuhammadSawalhy** [comment]
I have the same issue after configure **neoscroll** like this:

```lua
require('neoscroll').setup({
      hide_cursor = true,
})
```

**Comment by MuhammadSawalhy** [comment]
I have discovered a way to reproduce the issue, here it is

1. scroll with **neoscroll**, e.g. use `<C-d>` or `zz`
2. while scrolling, and before the scroll is completed, move the cursor again without **neoscroll**, e.g. `G` or `gg`

Now the cursor is hidden, ironically it appears when scrolling with **neoscroll** again, the opposite.

**Suggested fix**:

Neoscroll has to interrupt the other cases of navigation such as `g, G, w, e, W, <C-f>, <C-b>, ...` and make the cursor visible again and then perform the expected action.

**Comment by karb94** [comment]
@MuhammadSawalhy thank you for your steps to reproduce the problem. Can everyone check if 7cd46c1 fixes the issue? I think it definitely fixes your reproducible example but I don't know if there's some other edge cases left to fix.

**Comment by MuhammadSawalhy** [comment]
I think this fixes the issue:

![image](https://user-images.githubusercontent.com/42011920/129472754-07fa6d48-97a5-4dfa-b9e1-82d6b39fa94e.png)

**Comment by MuhammadSawalhy** [comment]
But when I tried to scroll up again, it scrolls one line only 😥.

**Comment by karb94** [comment]
try now (90c69cd).

**Comment by MuhammadSawalhy** [comment]
Now to disappears when I press `gg` while scrolling down, you have to test all cases as possible:

1. Scroll down + `G`
2. Scroll up + `G`
3. Scroll down + gg`
4. Scroll up + `gg`
5. Scroll down + `w`
6. Scroll up + `w`
7. .... etc

**Comment by oblitum** [comment]
[My report](https://github.com/karb94/neoscroll.nvim/issues/42#issuecomment-892922531) was a bit different as it was due to processor speed.

I pulled master and tested again on RPi3, still same problem.

**Comment by karb94** [comment]
@MuhammadSawalhy I think some of these issues are due to using a toggle to hide and unhide the cursor. When using another scroll command while scrolling the toggle may be used twice because of Neoscroll stop conditions at the edge of the buffer (when using `G`/`gg` after scrolling). I pushed a quick fix for now and will come up with a better solution later on. I couldn't reproduce the hidden cursor when using `w` during scroll so far. I can't think of anything that would be affected by it inside Neoscroll.

@oblitum does this last commit solve your problem by any chance?

**Comment by oblitum** [comment]
@karb94 yes, it's got fixed :)

**Comment by MuhammadSawalhy** [comment]
> does this last commit solve your problem by any chance?

Yes ♥️
