### ISSUE TITLE
Configure the speed of scrolling for all or for one

### ISSUE THREAD

**Issue by MuhammadSawalhy** [karb94/neoscroll.nvim#43]
I am trying to find a way to set the speed of the scrolling from the throw `require(...).setup({ time: 100 })`, but of course it is not working. After some searching, I found in `./lua/neoscroll/config.lua` this code:

https://github.com/karb94/neoscroll.nvim/blob/master/lua/neoscroll/config.lua#L3

There is no way to configure the speed of **neoscroll**, except by modifying the plugin itself, or by using [custom mappings](https://github.com/karb94/neoscroll.nvim#custom-mappings):

https://github.com/karb94/neoscroll.nvim/blob/master/lua/neoscroll/config.lua#L37

----

I think it is very useful to able some option to control the speed easily, just one option:

```lua
require('neoscroll').setup({
      speed = 1.5 -- this will make the scroll x1.5 faster than default
})
```

**Comment by karb94** [comment]
mm I don't know if this is a good idea. Every type of scroll has a different speed assign to it by default (see [defaults](https://github.com/karb94/neoscroll.nvim/blob/7cd46c1e00de36062451101492b470502c514bf4/lua/neoscroll/config.lua#L40-50) table in `config.lua`). These defaults are chosen by me base on my personal liking. I presume that if someone wants to change the defaults they likely want to change the individual values of the transitions to their liking not necessarily just shift the default value of all of the animations. Given that, as you noted, there's an alternative to achieve what you want (i.e. through custom mappings) I won't be implementing this. I know it requires a few more lines of code but at the same time you have more fine-grained control of the scrolling animations (and it's just a copy-paste away!).
