### ISSUE TITLE
Cannot unset option 'guicursor'

### ISSUE THREAD

**Issue by hungrybirder** [karb94/neoscroll.nvim#45]
Hi @karb94 
Thank you for this great plugin.
Recently I got a problem.
Here is my reproduce steps.

1. Start nvim
2. type `:help`
3. type `<c-f>` got error
![image](https://user-images.githubusercontent.com/1021047/130162380-9461a329-45c9-451d-a6cb-e42e26745499.png)
4. type `:verbose map <c-f>`
![image](https://user-images.githubusercontent.com/1021047/130162429-4168f74b-b091-40af-8d9b-67847560ec4a.png)

nvim version
```bash
NVIM v0.6.0-dev+162-g2ae9ff128
Build type: Release
LuaJIT 2.1.0-beta3
```

neoscroll.nvim version: 54879c6957ee5e833924064ff7fc17c144502ae9

Some config from my init.vim
```vim
set guicursor=
```

```lua
require('neoscroll').setup({
    mappings = {'<C-u>', '<C-d>', '<C-b>', '<C-f>',
                '<C-y>', '<C-e>', 'zt', 'zz', 'zb'},
    hide_cursor = true,          -- Hide cursor while scrolling
    stop_eof = true,             -- Stop at <EOF> when scrolling downwards
    respect_scrolloff = false,   -- Stop scrolling when the cursor reaches the scrolloff margin of the file
    cursor_scrolls_alone = true, -- The cursor will keep on scrolling even if the window cannot scroll further
    easing = false,              -- easing_function will be used in all scrolling animations with some defaults
    easing_function = function(x) return math.pow(x, 2) end -- default easing function
})

local t = {}
-- Syntax: t[keys] = {function, {function arguments}}
t['<C-u>'] = {'scroll', {'-vim.wo.scroll', 'true', '8'}}
t['<C-d>'] = {'scroll', { 'vim.wo.scroll', 'true', '8'}}
t['<C-b>'] = {'scroll', {'-vim.api.nvim_win_get_height(0)', 'true', '7'}}
t['<C-f>'] = {'scroll', { 'vim.api.nvim_win_get_height(0)', 'true', '7'}}
t['<C-y>'] = {'scroll', {'-0.10', 'false', '20'}}
t['<C-e>'] = {'scroll', { '0.10', 'false', '20'}}
t['zt']    = {'zt', {'7'}}
t['zz']    = {'zz', {'7'}}
t['zb']    = {'zb', {'7'}}

require('neoscroll.config').set_mappings(t)
```

When I disable `neoscroll.nvim`, I get no error.

If my config or something wrong, please let me know.
Thanks.

**Comment by jaydorsey** [comment]
I'm seeing the same behavior.

Disabling neoscroll, the error goes away.

```
NVIM v0.6.0-dev+163-g599af7451
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/jemalloc/include -I/opt/homebrew/opt/gmp/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/jay/repos/neovim/build/config -I/Users/jay/repos/neovim/src -I/Users/jay/repos/neovim/.deps/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/Users/jay/repos/neovim/build/src/nvim/auto -I/Users/jay/repos/neovim/build/include
Compiled by jay@macbook.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/jay/repos/neovim/build/share/nvim"

Run :checkhealth for more info
```

My minimal vimrc:

```
call plug#begin('~/.vim/plugged')
Plug 'karb94/neoscroll.nvim'
call plug#end()

lua <<EOF
require('neoscroll').setup()
EOF
```

To reproduce:

1. Open up a file that's long enough to scroll
2. Scroll with neovim mappings

**Comment by karb94** [comment]
Does the error disappear if you `set termguicolors`? I thinkI know where the issue is.

**Comment by hungrybirder** [comment]
> Does the error disappear if you `set termguicolors`? I thinkI know where the issue is. Unfortunately I don't have access to my computer till Monday so hopefully this temporary fix works for you.

I have already set `vim.o.termguicolors = true` in my `bufferline.lua`

The error doesn't disappear.

**Comment by jaydorsey** [comment]
I have `set termguicolors` in my full vimrc file and see the issue.

**Comment by tredeneo** [comment]
I disable <C-f> from mappings ={} and error disappear

**Comment by karb94** [comment]
@hungrybirder @jaydorsey Is this issue specific to version 0.6? I can see that both of you are using that version and I can't reproduce the issue in version 0.5.

**Comment by hungrybirder** [comment]
> @hungrybirder @jaydorsey Is this issue specific to version 0.6? I can see that both of you are using that version and I can't reproduce the issue in version 0.5.

yes, I'm using `v0.6.0-dev+162-g2ae9ff128`.

I switch nvim to `v0.5.0` and get the same error.

![image](https://user-images.githubusercontent.com/1021047/130538155-71673640-de61-4860-8f34-422d2f826529.png)

**Comment by karb94** [comment]
Can you try the latest commit? This is a shot in the dark as I haven't been able to reproduce the issue but it may solve the issue.

**Comment by hungrybirder** [comment]
> Can you try the latest commit? This is a shot in the dark as I haven't been able to reproduce the issue but it may solve the issue.

I use the lastest commit and it works well.

Thank you for fixing this issue. 👍

**Comment by jaydorsey** [comment]
Fixed the issue for me as well. Thanks!
