### ISSUE TITLE
smooth scroll isnt working

### ISSUE THREAD

**Issue by vaibd** [karb94/neoscroll.nvim#46]
The only error I get is 
`There are some issues with your config, run :LualineNotices` and running that tells me that 'nvim_lsp' is deprecated in favour of 'nvim_diagnostics' and it disappears when I comment neoscroll lines in my config.

My config(.txt format for upload only) 
[init.txt](https://github.com/karb94/neoscroll.nvim/files/7763956/init.txt)
[neoscroll.txt](https://github.com/karb94/neoscroll.nvim/files/7763958/neoscroll.txt)

**Comment by karb94** [comment]
I don't know how you came to the conclusion that Neoscroll is causing you issues. Your error clearly indicates that you have a problem with Lualine (your status line) config. Specifically, your Lualine plugin moved to the new 'nvim_diagnostics' api which was previously under the 'nvim_lsp' api. There are probably some changes you need to make in your Lualine config, go check their repo and open an issue there if necessary. Neoscroll doesn't use any of these apis so this error message is definitely not related to Neoscroll.

Solve your issue with Lualine first and then open a new issue here if you are still having problems getting Neoscroll to work.
