### ISSUE TITLE
Smooth scroll not working

### ISSUE THREAD

**Issue by vaibd** [karb94/neoscroll.nvim#48]
I have it configured like in the attached file and it doesnt work.
:checkhealth doesn't show any error.

[init.txt](https://github.com/karb94/neoscroll.nvim/files/7829688/init.txt)
[neoscroll.txt](https://github.com/karb94/neoscroll.nvim/files/7829687/neoscroll.txt)

**Comment by karb94** [comment]
You should start by removing other variables such as other plugins. Try loading only Neoscroll and see if it works. If it doesn't first make sure that the plugin is loaded with `:PackerStatus`. If it's loaded then check what happend to the bindings that Neoscroll provides. For example, to see what is `<C-d>` bound to you can use `:verbose map <C-d>`. If it's not bound to a neoscroll function then you have something in your config that overwrites the binding.

**Comment by vaibd** [comment]
Output for `:verbose map <C-d>`
![2022-01-08-12-571](https://user-images.githubusercontent.com/38762713/148635854-25789f0a-3cb9-4fde-8352-686756bfab35.png)

I tried running nvim without any module, and its still same and yes, the plugin is loaded. 
<C-d> works fine for smooth scrolling.

**Comment by karb94** [comment]
> \<C-d\> works fine for smooth scrolling.

So what does not work?

**Comment by vaibd** [comment]
oh lol, I thought this was supposed to make mouse scroll smooth.
Sorry 

I will bind it to
`map <ScrollWheelDown> <C-d>`

Maybe you should include this.

**Comment by vaibd** [comment]
Sorry this is unrelated to your plugin, but I tried mapping scrollup to `c-y` and  it isnt working.
The line I used for this
`map('n', '<ScrollWheelUp>', '<c-y>', { noremap = true })`

**Comment by vaibd** [comment]
It works with this but it isn't smooth, it stutters sometimes.

`map('n', '<ScrollWheelUp>', '<c-y>', { silent = true })`
`map('n', '<ScrollWheelDown>', '<c-e>', { silent = true })`

**Comment by karb94** [comment]
I did some quick testing and it won't be as simple as a mapping. I get some stutters from time to time as you do. look into this when I have time to see if it can be done. I'll open a new issue to make the feature request clear for anyone looking for it. If you have any suggestions post them there
