### ISSUE TITLE
Smooth scroll with mouse wheel (`<ScrollWheelUp>`/`<ScrollWheelDown>`)

### ISSUE THREAD

**Issue by karb94** [karb94/neoscroll.nvim#50]
Simply binding `<ScrollWheelUp>`/`<ScrollWheelDown>` to the scroll function doesn't quite work as there's some stuttering from time to time. I need to investigate what is the issue is and see if it can be fixed.

**Comment by vaibd** [comment]
This could be helpful [https://stackoverflow.com/questions/4064651/what-is-the-best-way-to-do-smooth-scrolling-in-vim](url)

**Comment by justinhj** [comment]
I think the link should be:
[https://stackoverflow.com/questions/4064651/what-is-the-best-way-to-do-smooth-scrolling-in-vim](https://stackoverflow.com/questions/4064651/what-is-the-best-way-to-do-smooth-scrolling-in-vim)

**Comment by ignamartinoli** [comment]
For now I fixed it with this
```lua

vim.keymap.set('n', '<ScrollWheelUp>', '<C-y>')
vim.keymap.set('n', '<ScrollWheelDown>', '<C-e>')
vim.keymap.set('i', '<ScrollWheelUp>', '<C-y>')
vim.keymap.set('i', '<ScrollWheelDown>', '<C-e>')
vim.keymap.set('v', '<ScrollWheelUp>', '<C-y>')
vim.keymap.set('v', '<ScrollWheelDown>', '<C-e>')

require 'neoscroll'.setup {
	mappings = { '<C-y>', '<C-e>' },
}
```

**Comment by champignoom** [comment]
Mapping each ScrollWheel events to `<C-y>/<C-e>` will make the scrolling in a constant slow speed.

A better way would be to first count the number of incoming ScrollWheel events, calculate the offset, and then scroll only once.
