### ISSUE TITLE
Disable smooth scroll in small windows... 

### ISSUE THREAD

**Issue by MuhammadSawalhy** [karb94/neoscroll.nvim#51]
Is there any option to disable smooth scroll in small-height windows, I think it is better to scroll these few lines immediately without experiencing this **_non-smooth_** scroll.

https://user-images.githubusercontent.com/42011920/155230395-03f58b80-7e16-4f33-b075-11071be9928f.mp4

**Comment by karb94** [comment]
I understand your concern but this functionality is out of scope for this plugin. The plugin just provides a function (`neoscroll.scroll()`) you can use to scroll smoothly a number of lines. You decide when to use that function. I provide some mappings that everyone would expect but that's about it.

What you want to do is map your scrolling keys to a function that checks if the window is high enough for your liking before calling `neoscroll.scroll()`. Unfortunately, I don't have the time to provide an example but should be pretty straightforward.
