### ISSUE TITLE
Support for `{` and `}`

### ISSUE THREAD

**Issue by axieax** [karb94/neoscroll.nvim#55]
Would love to see this plugins support smooth scrolling for curly braces navigation (which seems to be a popular navigation method for some users).

**Comment by karb94** [comment]
This plugin aims to add smooth scrolling support for all window scrolling commands (`:h scrolling`). I don't think it's worth going down the rabbit hole of supporting every motion command that may indirectly move the window. Maybe it's more adequate to cover these use cases in the wiki instead so that people can share their own wrapper functions for different motions. Some useful once that come to mind are `n`/`N` and `#`/`*`.

**Comment by axieax** [comment]
Fair enough haha. In that case, what should the number of lines be for this motion, or would I need Treesitter to determine that?

**Comment by karb94** [comment]
You would need a function that dynamically looks for the next start/end of a paragraph (`: h paragraph`) and calculates the number of lines that you would need to scroll to get there and pass them to `require('neoscroll').scroll()`. No need for Treesitter. I may add some functions for the motions I care about in the wiki when I have time.

**Comment by axieax** [comment]
Ahh I see. Is there a way to define a dynamic function for this use case?

**Comment by samEngineering** [comment]
Anyone made any headway on this? I would love to have this feature. I've been looking through
`:h paragraph`
`:h lines`
`:h nvim_buf_get_lines`

and playing around with things like
`/^$`
 
but can't quite put it together to get the number of lines. I'll post here if I find a way and I'll be super grateful if someone else does as well!

**Comment by roobert** [comment]
Thanks for the plugin @karb94!

I packaged paragraph support as a separate plugin, hope it helps! https://github.com/roobert/neoscroll-paragraph.nvim

**Comment by samEngineering** [comment]
Thanks so much @roobert!

I'm working out how to emulate the '}' motion by ignoring sequential blank lines.
Your solutions is awesome! Thanks for sharing. Here's what I've come up with so far based on yours:

```
--> heavily inspired by roobert/neoscroll-paragraph.vim  
--> thanks roobert! 
function next_paragraph_line_count(search_direction)                                                                                                     
   local current_line = vim.api.nvim_win_get_cursor(0)[1]
   local next_paragraph = vim.fn.search("\\(^$\\)\\(\\n^$\\)\\@!", search_direction)
   local distance_to_scroll = next_paragraph - current_line
   return distance_to_scroll                                                              
end

require('neoscroll.config').set_mappings({                                                                                                                               
   ['J'] = {'scroll', { 'next_paragraph_line_count("n")', 'false', '50'}},                                                                                                             
   ['K'] = {'scroll', { 'next_paragraph_line_count("b")', 'false', '50'}},    
})                                                                                            
```

The regex argument in `vim.fn.search()` will ignore segments of blank lines together. It looks for the next blank line that is not followed by another blank line. It's still a little buggy, but I'm still reading about all the settings available within this plugin so hopefully I can get it smoothed out.
