### ISSUE TITLE
neoscroll.G is not moving cursor to the last line

### ISSUE THREAD

**Issue by gnituy18** [karb94/neoscroll.nvim#56]
Hitting `G` only scrolling the file to the end but the cursor still remains at the same position.

https://user-images.githubusercontent.com/7200393/170806635-daa64ea0-c0e0-4e53-95ba-968917aadf5b.mov

Perhaps it should be
```
neoscroll.scroll(lines+win_lines_below_cursor, true, corrected_time, easing, { G = true })
```
 in [line 395](https://github.com/karb94/neoscroll.nvim/blob/master/lua/neoscroll/init.lua#L359) ?

**Comment by karb94** [comment]
`G` and `gg` support is not ready yet. It's quite tricky and there are still [some decisions to make](https://github.com/karb94/neoscroll.nvim/issues/23#issuecomment-939351617).
