### ISSUE TITLE
scrolling jumps up and down

### ISSUE THREAD

**Issue by xsteadfastx** [karb94/neoscroll.nvim#57]
since the last commit my scrolling via ctrl+d and ctrl+u jumps around. i recorded my screen to show it. thanks for this great plugin!

https://user-images.githubusercontent.com/168397/173810187-36823c8a-0701-438d-bdf5-843c5736d6fb.mp4

**Comment by mattiasbonte** [comment]
I can also confirm that I've been experiencing the same behavior during the last 2 days. It overshoots and keeps going until the end/beginning of the page. It also jumps back up while holding `C-d` or vice versa for `C-u`.

I've uninstalled the plugin and removed it's local files, reinstalled it, but without success.

I don't know if it's useful to provide our config, but if it would be needed I can provide it.

**Comment by karb94** [comment]
I'm sorry to hear that. I clearly didn't test the changes well enough.  I've reverted the last commit so if you pull the changes you should be good to go. Can any of you provide the Neoscroll config that reproduces this behaviour?

**Comment by omarahm3** [comment]
I had the same exact issue till @karb94 reverted the last commit.

Also i'm not using any custom config, i used the defaults and having it like this on my config:

```
	use({
		"karb94/neoscroll.nvim", -- pretty smooth scrolling
		config = function()
			require("neoscroll").setup({})
		end,
	})
```

**Comment by xsteadfastx** [comment]
for me too. i just used the basic setup.

**Comment by xsteadfastx** [comment]
should i close this issue? or let it open?

**Comment by mattiasbonte** [comment]
My config:
```
------------
-- CONFIG -- "https://github.com/karb94/neoscroll.nvim#options"
------------
require("neoscroll").setup({
	hide_cursor = true, -- Hide cursor while scrolling
	stop_eof = true, -- Stop at <EOF> when scrolling downwards
	use_local_scrolloff = false, -- Use the local scope of scrolloff instead of the global scope
	respect_scrolloff = false, -- Stop scrolling when the cursor reaches the scrolloff margin of the file
})
```
Very basic, the revert has fixed the behavior for me thank you for that, and also thanks for the awesome plugin!

**Comment by karb94** [comment]
@xsteadfastx  leave the issue open as a reminder for me. I'll close it when I fix the issue.

**Comment by xsteadfastx** [comment]
ok :) thanks

**Comment by karb94** [comment]
I think the last commit should help with this issue. happy to reopen if someone still experiences issues with this

**Comment by Patitotective** [comment]
Hi, I just wanted to share that I've been experiencing the same issue.
I'm using the latest version at the time (master f957373) but it still glitches when I do `<c-u>` and `<c-d>`.

**Comment by Patitotective** [comment]
~~Somehow, it got fixed when I changed my config like this:~~
```lua
{
  "karb94/neoscroll.nvim",
  opts = {

    mappings = {
      -- "<C-u>",
      -- "<C-d>",
      "<C-b>",
      "<C-f>",
      "<C-y>",
      "<C-e>",
      "zt",
      "zz",
      "zb",
    },
  },
}

```

---

**EDIT:** It seems neoscroll was conflicting with another plugin that provided smooth scrolling. I didn't need neoscroll.
