### ISSUE TITLE
zz is not centered

### ISSUE THREAD

**Issue by tobealive** [karb94/neoscroll.nvim#61]
A really minor issue but maybe theres a quick fix.

Using <kbd>zz</kbd> with nescroll wont result in redrawing the cursor line at the exact center of the window.

The video below shows execution of zz from some postions. With the used zoom level it results in 28 lines above the cursor and 26 below. 

https://user-images.githubusercontent.com/34311583/177830711-4b05b215-3bd4-4c2f-b49a-25dc484fd67e.mp4

Using <kbd>zz</kbd> without nescroll results in exact centering - 27 lines above and below the cursor.

Maybe I missed it, but is there already something that allows defining an offset for  <kbd>z</kbd> commands used with neoscroll?

---

edit:
I should have checked better before as it is clear when reading the code that one line is added. But I cannot quite follow why the +1 is added. Removing it results in centering the cursorline with zz.
https://github.com/karb94/neoscroll.nvim/blob/71c8fadd60362383e5e817e95f64776f5e2737d8/lua/neoscroll/init.lua#L333

**Comment by karb94** [comment]
I was trying to make it work for an odd number of lines but I messed up the case were you have an even number of lines in the window. Anyways, now should be fixed.
