### ISSUE TITLE
Feature: offset setting for `z*`

### ISSUE THREAD

**Issue by ttytm** [karb94/neoscroll.nvim#67]
I would like to be able to further customize scrolling motions in neovim. Specifically the `z` motions. 

E.g. that `zt` won't go to scroll-off but  would stop a little below.
Such an offset could be implemented as far as I can see fairly easy into the current codebase. 
If it helps - and if you can imagine implementing something like this - I could make a PR in the coming days.

I think this would give neoscroll another nice and distinct functionality. For some maybe just one, or one more reason to use it.

**Comment by karb94** [comment]
Either set the `scrolloff` to your desired value or use the `pre_hook`/`post_hook` functions to change the `scrolloff` value before the animation and reset it after. This is exactly why I created these hooks.

**Comment by ttytm** [comment]
Awesome! Thank you, the hooks will do the job!
