### ISSUE TITLE
move content of .vim file to explicit lua initialisation by user

### ISSUE THREAD

**Issue by matu3ba** [karb94/neoscroll.nvim#7]
I like the plugin very much. Thanks alot for creating!

Reasons to do:
1. A pure lua profile would decrease startup time.
2. The lua startup profiler would be more correct or simpler to get correct with this change. Otherwise one gets more wrong results.
3. Try to be consistent as to use functionality of lua, if possible.
4. Having a function to initialize makes separating things for user-specific settings while getting updates much easier (user may implement a different function to customize plugin).

Another related reason (bad practice/historical reasons): https://github.com/nvim-treesitter/module-template/issues/1

Relevant content for change:
https://github.com/nanotee/nvim-lua-guide#using-meta-accessors-1

Is the problem potentially that there is standard way to define description + maintainer for tools to read?
```vim
" Smooth scrolling plugin
" Maintainer: Carles Rafols i Belles
```

Sidenode: Luajit caches stuff (for speed reasons), so when no vimscript is involved or a function changes settings, they will remain.

**Comment by karb94** [comment]
Thank you for letting me know about this. The only reason why I haven't done this yet is my ignorance :) (this is my first plugin). I'll look into this.

**Comment by karb94** [comment]
See if the changes in 90d8f58 are sufficient. The README.md has a sample setup function you can copy.
