### ISSUE TITLE
Cursor moves up one line when using zb

### ISSUE THREAD

**Issue by sQVe** [karb94/neoscroll.nvim#71]
👋🏼 

I'm noting that when I press `zb` the cursor moves up one line. I can reproduce with:
- Open a large enough file.
- Alternate between inputting `zz` and `zb`.
- Note the cursor moving up one line.

See sceencast:

https://user-images.githubusercontent.com/2284724/198908232-978aff86-dd52-407d-9231-921e90603af2.mp4

**Comment by Jendker** [comment]
It can be reproduced if winbar is active.
To reproduce:
1. Add `vim.opt.winbar = "dummy_winbar"` to config
2. Open a long file (at least 2 screens long)
3. Move to middle of the file
6. Each press of `zb` will move editor one line up <--- not expected

**Comment by karb94** [comment]
The last commit (605a033) should fix this
