### ISSUE TITLE
Stop at end of file

### ISSUE THREAD

**Issue by ChristianChiarulli** [karb94/neoscroll.nvim#72]
![image](https://user-images.githubusercontent.com/29136904/201798223-c3f24bdb-adb9-46f9-8f07-774d007c4629.png)

![image](https://user-images.githubusercontent.com/29136904/201798303-bc309b1f-984f-4c51-8070-3548ddd8c733.png)

I want the scolling to stop at the last line like in the first picture not sure if this is already configurable

**Comment by karb94** [comment]
Doesn't the `stop_eof` option do what you want? Try this:
```lua
require('neoscroll').setup {
    stop_eof = false,
}
```

**Comment by LostNeophyte** [comment]
> Doesn't the `stop_eof` option do what you want? Try this:
> 
> ```lua
> require('neoscroll').setup {
>     stop_eof = false,
> }
> ```

For me it doesn't matter if the option is set to true or false, it will still scroll like in the first mp4 of my pr
