### ISSUE TITLE
Feature request - `zt`, `zb`, `zz` smoothed.

### ISSUE THREAD

**Issue by talbergs** [karb94/neoscroll.nvim#8]
With an option, to highlight the cursor line only using `hl-Search` group, during the scroll (i.e. for `zt` and `zb` binding only).

**Comment by karb94** [comment]
This is a reasonable feature to implement. I'll just need to make a wrapper over the main function. I'm not quite sure about the part about highlighting the cursor line during the scroll though. If you want to keep track of your cursor line why don't you `set cursorline` in the first place? A more general solution might be to add a pre-scrolling and post-scrolling hooks where you can pass functions and change settings as you please but this would be a separate feature for the future.

I'll work on getting `zt`, `zb` and `zz` working for now.

**Comment by talbergs** [comment]
Yes, by using hooks I could set `cursorline` only during scroll (as I do use it).
Also, I noticed another potential improvement - when using `<c-d>` that would not result in a scroll, then only cursor will "slide" (I'd suggest it jumped instead). This is debatable...

**Comment by karb94** [comment]
I have opened a separate issue for the hooks ( #10 ) . Feel free to comment about that there. I am not sure about the "cursor jump" when the window cannot scroll anymore. The whole point of the plugin is to smoothly move the window and/or cursor. You can open an issue and if there is enough interest I'll consider it.
