### ISSUE TITLE
works not very with wrapped lines.

### ISSUE THREAD

**Issue by cathaysia** [karb94/neoscroll.nvim#82]
It seems #13 fixed this problem. But it not works very well:

https://user-images.githubusercontent.com/42114817/226256694-ab659534-3565-4dc4-aece-1ea10854334b.mp4

As you see. When I press ctrl-d, then line numer become 43. But expected 21. :(

**Comment by cathaysia** [comment]
here is that file: [shared-libraries.adoc.txt](https://github.com/karb94/neoscroll.nvim/files/11014528/shared-libraries.adoc.txt)

> copy from https://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html

**Comment by karb94** [comment]
Apologies, I missed this issue. Dealing with wrapped lines is notoriously difficult. If you use `<C-d>`/`<C-u>` in your document you'll notice that while the number of lines you move is more or less respected your cursor ends up on different heights. Essentially you need to choose to either respect the amount of lines moved or the height of the cursor. For scrolling my opinion is that keeping the cursor at the same height during the scrolling animation (and final position) is preferable and what most people would expect.

**Comment by cathaysia** [comment]
Thank you. In fact, except when writing asciidoc, I rarely encounter the problem of too long lines.  Currently I often use visual rows to move the cursor
