### ISSUE TITLE
Simply not working

### ISSUE THREAD

**Issue by druskus20** [karb94/neoscroll.nvim#89]
NVIM v0.9.2
lazy.nvim 
```
    require("lazy").setup({
        { "karb94/neoscroll.nvim" }
    })
```

Lazy loads the plugin correctly
![image](https://github.com/karb94/neoscroll.nvim/assets/43417195/a05aca4c-c9ad-4b1d-90b6-fd31e213abe2)

However, using <C+d> or <C+u> does not work. Neither does any of the other mappings afaik.

**Comment by suhdonghwi** [comment]
Hello, I am not a maintainer but I have a suggestion. Have you configured to call the setup function?
```
require('neoscroll').setup()
```

**Comment by Rahim-444** [comment]
It doesn't work if you have a keymap set for <C-u> or <C-d>, for me I have <C-d> mapped to <C-d>zz and when I disable the keymap it works fine.
