### ISSUE TITLE
bug: setting new mappings adds binding for ESC key 

### ISSUE THREAD

**Issue by Coombszy** [karb94/neoscroll.nvim#96]
Following these instructions:
```lua
require('neoscroll').setup({
    -- Set any options as needed
})

local t = {}
-- Syntax: t[keys] = {function, {function arguments}}
t['<C-u>'] = {'scroll', {'-vim.wo.scroll', 'true', '250'}}
t['<C-d>'] = {'scroll', { 'vim.wo.scroll', 'true', '250'}}
t['<C-b>'] = {'scroll', {'-vim.api.nvim_win_get_height(0)', 'true', '450'}}
t['<C-f>'] = {'scroll', { 'vim.api.nvim_win_get_height(0)', 'true', '450'}}
t['<C-y>'] = {'scroll', {'-0.10', 'false', '100'}}
t['<C-e>'] = {'scroll', { '0.10', 'false', '100'}}
t['zt']    = {'zt', {'250'}}
t['zz']    = {'zz', {'250'}}
t['zb']    = {'zb', {'250'}}

require('neoscroll.config').set_mappings(t)
```
Results in a situation where pressing the escape key scrolls up the buffer.

Using MacOS and Alacritty.

**Comment by karb94** [comment]
What does `:verbose map <esc>` return?

**Comment by Coombszy** [comment]
Hi!
this results in `No mapping found`

**Comment by karb94** [comment]
1. Does this happen when you don't run the line with `set_mappings(t)`?
2. Does this happen when you don't add any (or some) of the `t['XYZ'] = {.....}` lines? What line triggers it?
3. Can you try running Neoscroll without any other plugins installed?

I would be very surprised if this is a Neoscroll issue

**Comment by karb94** [comment]
Closing since there's been no reply from OP in a while
