### ISSUE TITLE
Options not working anymore

### ISSUE THREAD

**Issue by niekdomi** [karb94/neoscroll.nvim#98]
Recently the options have stopped working. e.g.  the following options no longer have any effect, regardless whether the flag is true or false.
 
```
stop_eof = true, -- Stop at <EOF> when scrolling downwards
respect_scrolloff = false, -- Stop scrolling when the cursor reaches the scrolloff margin of the file
```

But also the scrolling speed can't be changed anymore

```
t["<C-u>"] = { "scroll", { "-vim.wo.scroll", "true", "1000", [['sine']] } }
```

As per my understanding "1000" should be visibly slow, but it's just as fast as if I leave it commented out

I'm using neovim version v.0.9.5

I'm not sure if this issue is due to my configs, but if I remember correctly, the flags  worked before I updated to the latest version

**Comment by karb94** [comment]
Both configs work fine for me. What is the output of `:verbose map <C-u>`?

**Comment by karb94** [comment]
Do you get the same if you set `mappings=nil`? Are you sure you haven't defined `Neoscroll` somewhere else? If you remove this config is Neoscroll still getting loaded by any chance?
